### [관리자]한 개 카테고리 생성하기
POST http://localhost:19010/api/v1/admin/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk3ODMwLCJpYXQiOjE3NDAyMTE0MzB9.ci8hr1TGI1LE6BS_SyJsB1fKWFWdDx5IKbvLo8jg3ro

{
  "name": "맛있는카테고리"
}

### [관리자]두 개 이상 카테고리 생성하기
POST http://localhost:19010/api/v1/admin/categories/batch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk3ODMwLCJpYXQiOjE3NDAyMTE0MzB9.ci8hr1TGI1LE6BS_SyJsB1fKWFWdDx5IKbvLo8jg3ro


[
  {
    "name": "일식"
  },
  {
    "name": "중식"
  },
  {
    "name": "한식"
  }
]

### [관리자]모든 카테고리 조회하기
GET http://localhost:19010/api/v1/admin/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk3ODMwLCJpYXQiOjE3NDAyMTE0MzB9.ci8hr1TGI1LE6BS_SyJsB1fKWFWdDx5IKbvLo8jg3ro


// @categoryId=카테고리 UUID
### [관리자]단 건 카테고리 수정하기
PATCH http://localhost:19010/api/v1/admin/categories/77e20f36-f990-4ee2-9387-bd097b237582
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk3ODMwLCJpYXQiOjE3NDAyMTE0MzB9.ci8hr1TGI1LE6BS_SyJsB1fKWFWdDx5IKbvLo8jg3ro

{
  "name": "수정된 카테고리1",
  "isActive": true
}


### [관리자]단 건 카테고리 소프트 삭제하기
DELETE http://localhost:19010/api/v1/admin/categories/77e20f36-f990-4ee2-9387-bd097b237582
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk3ODMwLCJpYXQiOjE3NDAyMTE0MzB9.ci8hr1TGI1LE6BS_SyJsB1fKWFWdDx5IKbvLo8jg3ro


### [모든사용자]모든 카테고리 조회하기
GET http://localhost:19010/api/v1/categories?name=일식&page=0&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJhdXRoIjoiTUFTVEVSIiwiZXhwIjoxNzQwMjk3ODMwLCJpYXQiOjE3NDAyMTE0MzB9.ci8hr1TGI1LE6BS_SyJsB1fKWFWdDx5IKbvLo8jg3ro

