### 회원 생성하기 (권한 X)
POST http://localhost:19010/api/auth/signup
Content-Type: application/json

{
  "userEmail": "test1@gmail.com",
  "password": "test1234!",
  "name": "박길동",
  "nickname": "asd124",
  "phone": "010-1234-1235",
  "address": {
    "bcode": "1234567890",
    "jibunAddress": "서울시 강남구 역삼동 777-77",
    "roadAddress": "서울특별시 강남구 테헤란 777",
    "detail": "1층, 우측 코너"
  },
  "role": "MASTER"
}

### 회원 로그인하기 (권한 X)
POST http://localhost:19010/api/auth/signin
Content-Type: application/json

{
  "userEmail" : "test1@gmail.com",
  "password" : "test1234!"
}